FROM node:18-alpine AS development

WORKDIR /app

COPY package.json yarn.lock ./

EXPOSE 3000

RUN yarn add react-scripts@latest && yarn install

COPY . .

CMD ["npm", "run", "dev"]

FROM node:16-alpine AS production

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn add react-scripts@latest && yarn install

COPY . .

RUN yarn build 

EXPOSE 3000

CMD ["yarn","run","start"]